--==========================================================================================================================
-- LANGUAGE_EN_US
--==========================================================================================================================	
------------------------------
-- Promotion Names
------------------------------
UPDATE Language_en_US SET Text = 'Highlanders' WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY';
UPDATE Language_en_US SET Text = 'Legend of the Five Suns' WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';
UPDATE Language_en_US SET Text = 'Myriad' WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_HEAL';
UPDATE Language_en_US SET Text = 'Barbarian Penalty I' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_I';
UPDATE Language_en_US SET Text = 'Barbarian Penalty II' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_II';
UPDATE Language_en_US SET Text = 'Barbarian Penalty III' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_III';
UPDATE Language_en_US SET Text = 'Anti-Helicopter' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';
UPDATE Language_en_US SET Text = 'Anti-Submarine I' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I';
UPDATE Language_en_US SET Text = 'Anti-Submarine II' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II';
UPDATE Language_en_US SET Text = 'Anti-Fighter' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_FIGHTER';
--10
UPDATE Language_en_US SET Text = 'Anti-Gunpowder' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_GUNPOWDER';
UPDATE Language_en_US SET Text = 'Anti-Mounted I' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I';
UPDATE Language_en_US SET Text = 'Anti-Mounted II' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_II';
UPDATE Language_en_US SET Text = 'Anti-Tank' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK';
UPDATE Language_en_US SET Text = 'Deep Water Inaccuracy' WHERE Tag = 'TXT_KEY_PROMOTION_BIG_CITY_PENALTY';
UPDATE Language_en_US SET Text = 'Mobile Forces' WHERE Tag = 'TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING';
UPDATE Language_en_US SET Text = 'Ice Explorer' WHERE Tag = 'TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE';
UPDATE Language_en_US SET Text = 'Cargo Bay I' WHERE Tag = 'TXT_KEY_PROMOTION_CARGO_I';
UPDATE Language_en_US SET Text = 'Cargo Bay II' WHERE Tag = 'TXT_KEY_PROMOTION_CARGO_II';
UPDATE Language_en_US SET Text = 'Cargo Bay III' WHERE Tag = 'TXT_KEY_PROMOTION_CARGO_III';
--20
UPDATE Language_en_US SET Text = 'Cargo Bay IV' WHERE Tag = 'TXT_KEY_PROMOTION_CARGO_IV';
UPDATE Language_en_US SET Text = 'Siege Penalty' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY';
UPDATE Language_en_US SET Text = 'Great City Assault' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT';
UPDATE Language_en_US SET Text = 'Siege Engine I' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE';
UPDATE Language_en_US SET Text = 'Siege Engine II' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_II';
UPDATE Language_en_US SET Text = 'Air Siege I' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1';
UPDATE Language_en_US SET Text = 'Air Siege II' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2';
UPDATE Language_en_US SET Text = 'Air Siege III' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3';
UPDATE Language_en_US SET Text = 'Capital Protector' WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL';
UPDATE Language_en_US SET Text = 'Defenseless' WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSE_PENALTY';
--30
UPDATE Language_en_US SET Text = 'Air Range' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_RANGE';
UPDATE Language_en_US SET Text = 'Evasion I' WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_I';
UPDATE Language_en_US SET Text = 'Evasion II' WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_II';
UPDATE Language_en_US SET Text = 'Evasive Manouvers' WHERE Tag = 'TXT_KEY_PROMOTION_EVASION';
UPDATE Language_en_US SET Text = 'Extra Movement' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_MOVES_I';
UPDATE Language_en_US SET Text = 'Extra Sight I' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_I';
UPDATE Language_en_US SET Text = 'Extra Sight II' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_II';
UPDATE Language_en_US SET Text = 'Extra Sight III' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_III';
UPDATE Language_en_US SET Text = 'Extra Sight IV' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_IV';
UPDATE Language_en_US SET Text = 'Embarked Vision' WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKED_SIGHT';
--40
UPDATE Language_en_US SET Text = 'Flight' WHERE Tag = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST';
UPDATE Language_en_US SET Text = 'Naval Siege' WHERE Tag = 'TXT_KEY_PROMOTION_FIRE_SUPPORT';
UPDATE Language_en_US SET Text = 'Dangerous Woods' WHERE Tag = 'TXT_KEY_PROMOTION_FOLIAGE_IMPASSABLE';
UPDATE Language_en_US SET Text = 'Expeditionary' WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS';
UPDATE Language_en_US SET Text = 'Pillager' WHERE Tag = 'TXT_KEY_PROMOTION_FREE_PILLAGE_MOVES';
UPDATE Language_en_US SET Text = 'Advisor' WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING';
UPDATE Language_en_US SET Text = 'Golden Boy' WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS';
UPDATE Language_en_US SET Text = 'Heavy Payload' WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_PAYLOAD';
UPDATE Language_en_US SET Text = 'Air-to-surface Missiles I' WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1';
UPDATE Language_en_US SET Text = 'Air-to-surface Missiles II' WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2';
--50
UPDATE Language_en_US SET Text = 'Air Reconnaissance I' WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_1';
UPDATE Language_en_US SET Text = 'Air Reconnaissance II' WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_2';
UPDATE Language_en_US SET Text = 'Total Recovery' WHERE Tag = 'TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY';
UPDATE Language_en_US SET Text = 'Instant Heal' WHERE Tag = 'TXT_KEY_PROMOTION_HEAL_INSTANTLY';
UPDATE Language_en_US SET Text = 'Terrain Maps' WHERE Tag = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST';
UPDATE Language_en_US SET Text = 'Squadron I' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_I';
UPDATE Language_en_US SET Text = 'Squadron II' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_II';
UPDATE Language_en_US SET Text = 'Squadron III' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_III';
UPDATE Language_en_US SET Text = 'Squadron IV' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_IV';
UPDATE Language_en_US SET Text = 'Invisibility' WHERE Tag = 'TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE';
--60
UPDATE Language_en_US SET Text = 'Forest Tribe' WHERE Tag = 'TXT_KEY_PROMOTION_JAGUAR';
UPDATE Language_en_US SET Text = 'Vampirism' WHERE Tag = 'TXT_KEY_PROMOTION_KILL_HEAL';
UPDATE Language_en_US SET Text = 'Knockout I' WHERE Tag = 'TXT_KEY_PROMOTION_KNOCKOUT_I';
UPDATE Language_en_US SET Text = 'Knockout II' WHERE Tag = 'TXT_KEY_PROMOTION_KNOCKOUT_II';
UPDATE Language_en_US SET Text = 'Kaniengehawa' WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK';
UPDATE Language_en_US SET Text = 'Mechanized Division' WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_ARMOR';
UPDATE Language_en_US SET Text = 'Infantry Division' WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_GUN';
UPDATE Language_en_US SET Text = 'Horsepower' WHERE Tag = 'TXT_KEY_PROMOTION_MOUNTED_PENALTY';
UPDATE Language_en_US SET Text = 'Convoi' WHERE Tag = 'TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL';
UPDATE Language_en_US SET Text = 'Difficult Terrain' WHERE Tag = 'TXT_KEY_PROMOTION_MUST_SET_UP';
--70
UPDATE Language_en_US SET Text = 'Arrows and Bullets' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_MISFIRE';
UPDATE Language_en_US SET Text = 'Naval Targeting' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_BONUS';
UPDATE Language_en_US SET Text = 'Trenches' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_INACCURACY';
UPDATE Language_en_US SET Text = 'Extended Morale' WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_EVENT';
UPDATE Language_en_US SET Text = 'Hard Broadsides' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_PENALTY';
------------------------------
-- Promotion Pedia Entries
------------------------------
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_TANK' WHERE Type = 'PROMOTION_ANTI_TANK';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_FIGHTER' WHERE Type = 'PROMOTION_ANTI_FIGHTER';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER' WHERE Type = 'PROMOTION_ANTI_HELICOPTER';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_AIR_RECON' WHERE Type = 'PROMOTION_AIR_RECON';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_AIR_SWEEP' WHERE Type = 'PROMOTION_AIR_SWEEP';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I' WHERE Type = 'PROMOTION_ANTI_MOUNTED_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_II' WHERE Type = 'PROMOTION_ANTI_MOUNTED_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ATTACK_BONUS' WHERE Type = 'PROMOTION_ATTACK_BONUS';
--10
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING' WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE' WHERE Type = 'PROMOTION_CAN_MOVE_IMPASSABLE';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY' WHERE Type = 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FASTER_HEAL' WHERE Type = 'PROMOTION_FASTER_HEAL';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CARGO_I' WHERE Type = 'PROMOTION_CARGO_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CARGO_II' WHERE Type = 'PROMOTION_CARGO_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CARGO_III' WHERE Type = 'PROMOTION_CARGO_III';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CARGO_IV' WHERE Type = 'PROMOTION_CARGO_IV';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CITY_ASSUALT' WHERE Type = 'PROMOTION_CITY_ASSAULT';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CITY_PENALTY' WHERE Type = 'PROMOTION_CITY_PENALTY';
--20
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CITY_SIEGE' WHERE Type = 'PROMOTION_CITY_SIEGE';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_DEFENSE_PENALTY' WHERE Type = 'PROMOTION_DEFENSE_PENALTY';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_EVASION_I' WHERE Type = 'PROMOTION_EVASION_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_EVASION_II' WHERE Type = 'PROMOTION_EVASION_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_XTRA_MOVES_I' WHERE Type = 'PROMOTION_EXTRA_MOVES_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_XTRA_SIGHT_I' WHERE Type = 'PROMOTION_EXTRA_SIGHT_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_XTRA_SIGHT_II' WHERE Type = 'PROMOTION_EXTRA_SIGHT_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_XTRA_SIGHT_III' WHERE Type = 'PROMOTION_EXTRA_SIGHT_III';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_XTRA_SIGHT_IV' WHERE Type = 'PROMOTION_EXTRA_SIGHT_IV';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST' WHERE Type = 'PROMOTION_FLAT_MOVEMENT_COST';
--30
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FOLIAGE_IMPASSABLE' WHERE Type = 'PROMOTION_FOLIAGE_IMPASSABLE';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FOREIGN_LANDS' WHERE Type = 'PROMOTION_FOREIGN_LANDS';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FREE_PILLAGE_MOVES' WHERE Type = 'PROMOTION_FREE_PILLAGE_MOVES';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_GREAT_GENERAL' WHERE Type = 'PROMOTION_GREAT_GENERAL';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY' WHERE Type = 'PROMOTION_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_HOVERING_UNIT' WHERE Type = 'PROMOTION_HOVERING_UNIT';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST' WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_INTERCEPTION_I' WHERE Type = 'PROMOTION_INTERCEPTION_I';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_INTERCEPTION_II' WHERE Type = 'PROMOTION_INTERCEPTION_II';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_INTERCEPTION_III' WHERE Type = 'PROMOTION_INTERCEPTION_III';
--40
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_INTERCEPTION_IV' WHERE Type = 'PROMOTION_INTERCEPTION_IV';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE' WHERE Type = 'PROMOTION_INVISIBLE_SUBMARINE';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_JAGUAR' WHERE Type = 'PROMOTION_JAGUAR';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_MOHAWK' WHERE Type = 'PROMOTION_MOHAWK';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_MOUNTED_PENALTY' WHERE Type = 'PROMOTION_MOUNTED_PENALTY';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_MUST_SET_UP' WHERE Type = 'PROMOTION_MUST_SET_UP';
UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_NAVAL_PENALTY' WHERE Type = 'PROMOTION_NAVAL_PENALTY';
------------------------------
-- Promotion Pedia Types
------------------------------
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_ARMOR_PLATING_1';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_ARMOR_PLATING_2';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_ARMOR_PLATING_3';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_AOE_STRIKE_FORTIFY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_AOE_STRIKE_ON_KILL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_AMBASSADOR';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_ALTITUDE_TRAINING';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_ANTI_MOUNTED_I';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_ANTI_MOUNTED_II';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_ANTI_TANK';
--10
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING';
UPDATE UnitPromotions SET PediaType = 'PEDIA_NAVAL' WHERE Type = 'PROMOTION_CAN_MOVE_IMPASSABLE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_NAVAL' WHERE Type = 'PROMOTION_BIG_CITY_PENALTY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_HEAL' WHERE Type = 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_HEAL' WHERE Type = 'PROMOTION_FASTER_HEAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_COAST_WALKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_CITY_ASSAULT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CITY_PENALTY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_CITY_SIEGE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_CITY_SIEGE_II';
--20
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_DIPLOMAT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_COVER_1';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_COVER_2';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_DEFEND_NEAR_CAPITAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_DEFENSE_PENALTY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_DESERT_WALKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_SKI_INFANTRY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_COERCION';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_ENSLAVEMENT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_DESERT_WARRIOR';
--30
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_EMISSARY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_ENVOY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_DOUBLE_PLUNDER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_EXTRA_MOVES_I';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_EXTRA_SIGHT_I';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_EXTRA_SIGHT_II';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_EXTRA_SIGHT_III';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_EXTRA_SIGHT_IV';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_EMBARKED_SIGHT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_EXPRESS';
--40
UPDATE UnitPromotions SET PediaType = 'PEDIA_HEAL' WHERE Type = 'PROMOTION_EVERLASTING_YOUTH';
UPDATE UnitPromotions SET PediaType = 'PEDIA_AIR' WHERE Type = 'PROMOTION_FLAT_MOVEMENT_COST';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_FLANK_ATTACK_BONUS';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_FALLOUT_REDUCTION';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_FALLOUT_IMMUNITY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_FAST_ADMIRAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_FAST_GENERAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_FASTER_GENERAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_FOLIAGE_IMPASSABLE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_FOREIGN_LANDS';
--50
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_FREE_PILLAGE_MOVES';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_GAIN_EXPERIENCE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_GENERAL_STACKING';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_GOLDEN_AGE_POINTS';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SCOUTING' WHERE Type = 'PROMOTION_GOODY_HUT_PICKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_GREAT_ADMIRAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_GREAT_DIPLOMAT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_GREAT_GENERAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_CIVILIAN' WHERE Type = 'PROMOTION_GREAT_MERCHANT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_HAKA_WAR_DANCE';
--60
UPDATE UnitPromotions SET PediaType = 'PEDIA_HEAL' WHERE Type = 'PROMOTION_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_AIR' WHERE Type = 'PROMOTION_HEAVY_PAYLOAD';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_HILL_WALKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_HOMELAND_GUARDIAN';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_HOMELAND_GUARDIAN_BOOGALOO';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';
UPDATE UnitPromotions SET PediaType = 'PEDIA_RANGED' WHERE Type = 'PROMOTION_INDIRECT_FIRE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_IMMUNITY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_LIGHTNING_WARFARE';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_LIGHTNING_WARFARE_ARMOR';
--70
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_LIGHTNING_WARFARE_GUN';
UPDATE UnitPromotions SET PediaType = 'PEDIA_DIPLO' WHERE Type = 'PROMOTION_LITERACY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_LOGISTICS';
UPDATE UnitPromotions SET PediaType = 'PEDIA_NAVAL' WHERE Type = 'PROMOTION_LONGBOAT';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_MARSH_WALKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_HEAL' WHERE Type = 'PROMOTION_MEDIC_GENERAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_MOBILITY';
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_MOON_STRIKER';
UPDATE UnitPromotions SET PediaType = 'PEDIA_MELEE' WHERE Type = 'PROMOTION_MOVEMENT_TO_GENERAL';
UPDATE UnitPromotions SET PediaType = 'PEDIA_NAVAL' WHERE Type = 'PROMOTION_NAVAL_INACCURACY';
--80
UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_NAVAL_PENALTY';
------------------------------
-- Promotion Descriptions Definitions
------------------------------
INSERT INTO Language_en_US
			(Tag,															Text)
VALUES		('TXT_KEY_PROMOTION_ANTI_TANK_HELP',							'+100% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_ANTI_FIGHTER_HELP',							'+33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Fighter Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP',						'+150% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Helicopter Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP',						'+33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Submarine Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_ANTI_SUBMARINE_II_HELP',					'+75% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Submarine Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP',				'Unit [COLOR_POSITIVE_TEXT]can Move again[ENDCOLOR] after Attack.'),
			('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP',					'Unit [COLOR_POSITIVE_TEXT]can Enter Ice[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY_HELP',		'+25 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR]'),
			('TXT_KEY_PROMOTION_FASTER_HEAL_HELP',							'+10 HP [COLOR_POSITIVE_TEXT]on Heal[ENDCOLOR]'), 
			('TXT_KEY_PROMOTION_CARGO_I_HELP',								'Unit can Carry [COLOR_POSITIVE_TEXT]1 Cargo[ENDCOLOR].'), --10
			('TXT_KEY_PROMOTION_CARGO_II_HELP',								'Unit can Carry [COLOR_POSITIVE_TEXT]2 Cargo[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_CARGO_III_HELP',							'Unit can Carry [COLOR_POSITIVE_TEXT]3 Cargo[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_CARGO_IV_HELP',								'Unit can Carry [COLOR_POSITIVE_TEXT]4 Cargo[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_EVASION_I_HELP',							'+50% Evasion Chance.'),
			('TXT_KEY_PROMOTION_EVASION_II_HELP',							'+80% Evasion Chance.'),
			('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP',					'Unit uses 1 [ICON_ARROW_RIGHT] Movement Point [COLOR_POSITIVE_TEXT]on every Feature and Terrain[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_FIRE_SUPPORT_HELP',							'33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_FOLIAGE_IMPASSABLE_HELP',					'Unit [COLOR_POSITIVE_TEXT]cannot Enter Forest or Jungle[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_FREE_PILLAGE_MOVES_HELP',					'Unit uses [COLOR_POSITIVE_TEXT]no[ENDCOLOR] [ICON_ARROW_RIGHT] Movement Points [COLOR_POSITIVE_TEXT]on Pillage[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_HEAVY_PAYLOAD_HELP',						'+50% [ICON_RANGED_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].'), --20
			('TXT_KEY_PROMOTION_HELI_AMBUSH_1_HELP',						'+25% [ICON_RANGED_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_HELI_AMBUSH_2_HELP',						'+25% [ICON_RANGED_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP',					'Unit [ICON_RANGED_STRENGTH]ignores Terrain Cost[ENDCOLOR].'),
			('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP',						'+20% Interception Chance.'),
			('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP',						'+40% Interception Chance.'),
			('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP',						'+50% Interception Chance.'),
			('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP',						'+100% Interception Chance.'),
			('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP',					'Unit [COLOR_POSITIVE_TEXT]is Invisible[ENDCOLOR] to other Enemy Units without special ability.'),
			('TXT_KEY_PROMOTION_MOUNTED_PENALTY_HELP',						'-33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR]. Lost after unit upgrade.'),
			('TXT_KEY_PROMOTION_MUST_SET_UP_HELP',							'Half [ICON_ARROW_RIGHT] Movement [COLOR_POSITIVE_TEXT]inside Enemy Territory[ENDCOLOR]. Lost after unit upgrade.'), --30
			('TXT_KEY_PROMOTION_NAVAL_PENALTY_HELP',						'-50% [ICON_STRENGTH] vs [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR].');
------------------------------
-- Promotion Descriptions
------------------------------
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units above 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_1_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units above 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_2_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units above 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_3_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units above 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_4_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_STRENGTH] Combat Strength. Additional +5% [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is adjacent to another Friendly Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE_HELP';
UPDATE Language_en_US SET Text = '+1 Interception per turn.' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP';
UPDATE Language_en_US SET Text = '+1 Interception per turn.' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_2_HELP';
UPDATE Language_en_US SET Text = '-30% [ICON_RANGE_STRENGTH] Ranged Combat Strength. Unit [COLOR_POSITIVE_TEXT]may Attack twice a turn[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LOGISTICS_HELP';
UPDATE Language_en_US SET Text = '+2 Range.' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_RANGE_HELP';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]reveals 6 tiles[ENDCOLOR] in every direction.' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_RECON_HELP';
--10
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]heals every turn[ENDCOLOR], even after performing an action. -10% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_MARCH_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP';
UPDATE Language_en_US SET Text = '+34% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP';
UPDATE Language_en_US SET Text = 'Unit can Air Sweep to [COLOR_POSITIVE_TEXT]clear Intercepting Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SWEEP_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Naval and Land Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Naval and Land Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_2_HELP';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]onto Water Tiles[ENDCOLOR]. Embarked Unit [COLOR_POSITIVE_TEXT]can Enter Ocean[ENDCOLOR] and has +1 [ICON_VIEW_CITY] Sight.' WHERE Tag = 'TXT_KEY_PROMOTION_ALLWATER_EMBARKATION_HELP';
UPDATE Language_en_US SET Text = 'Double [ICON_ARROW_RIGHT] Movement and +10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';
UPDATE Language_en_US SET Text = '+55 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_AMBASSADOR_HELP';
--20
UPDATE Language_en_US SET Text = '+30% [ICON_STRENGTH] Attack Bonus and +5% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Armor Units[ENDCOLOR] and +25% [ICON_STRENGTH] Attack Bonus [COLOR_POSITIVE_TEXT]in Rough Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_1_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Armor Units[ENDCOLOR] and +25% [ICON_STRENGTH] Attack Bonus [COLOR_POSITIVE_TEXT]in Rough Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_2_HELP';
UPDATE Language_en_US SET Text = 'Unit has no combat penalties for Attacking [COLOR_POSITIVE_TEXT]from the Sea or over a River[ENDCOLOR]. Bonus [ICON_ARROW_RIGHT] Movement Point[COLOR_POSITIVE_TEXT] after crossing Rivers[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AMPHIBIOUS_HELP';
UPDATE Language_en_US SET Text = '+150% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_HELP';
UPDATE Language_en_US SET Text = '+150% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_II_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Gunpowder Units[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_GUNPOWDER_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_TANK_HELP' WHERE Type = 'PROMOTION_ANTI_TANK';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP';
UPDATE Language_en_US SET Text = '+100% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP';
--30
UPDATE Language_en_US SET Text = 'Unit deals flat damage [COLOR_POSITIVE_TEXT]to attackng Air Unit[ENDCOLOR]. Available after researching Flight.' WHERE Tag = 'TXT_KEY_PROMOTION_ANTIAIR_LAND_I_HELP';
UPDATE Language_en_US SET Text = 'Unit deals flat damage [COLOR_POSITIVE_TEXT]to attackng Air Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ANTIAIR_LAND_II_HELP';
UPDATE Language_en_US SET Text = 'Unit deals flat damage [COLOR_POSITIVE_TEXT]to attackng Air Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ANTIAIR_LAND_III_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_FIGHTER_HELP' WHERE Type = 'PROMOTION_ANTI_FIGHTER';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP' WHERE Type = 'PROMOTION_ANTI_HELICOPTER';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_I';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II_HELP' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_II';
UPDATE Language_en_US SET Text = '[COLOR_POSITIVE_TEXT]At the beginning of each turn[ENDCOLOR] Enemy Unit takes flat damage if it [COLOR_POSITIVE_TEXT]is adjacent to Fortified Unit with this promotion[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AOE_STRIKE_FORTIFY_HELP';
UPDATE Language_en_US SET Text = '[COLOR_POSITIVE_TEXT]On Kill[ENDCOLOR] unit adavances and inflicts flat damage [COLOR_POSITIVE_TEXT]to all new adjacent Enemy Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AOE_STRIKE_ON_KILL_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_1_HELP';
--40
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_2_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_3_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength and +1 [ICON_ARROW_RIGHT] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_ARSENALE_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Attack Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_ATTACK_BONUS_HELP';
UPDATE Language_en_US SET Text = '+20% [ICON_STRENGTH] Attack Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_ATTACK_BONUS_SWEDEN_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Barbarians[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_BONUS_HELP';
UPDATE Language_en_US SET Text = '-30% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Barbarians[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_I_HELP';
UPDATE Language_en_US SET Text = '-20% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Barbarians[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_II_HELP';
UPDATE Language_en_US SET Text = '-10% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Barbarians[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_BARBARIAN_PENALTY_III_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units at or below 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_1_HELP';
--50
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units at or below 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_2_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +10% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Units at or below 50 HP[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_3_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]outside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_4_HELP';
UPDATE Language_en_US SET Text = 'Unit has more [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on lower Health[ENDCOLOR]. +5 HP [COLOR_POSITIVE_TEXT]on Heal to all adjacent Friendly Units[ENDCOLOR]. +10 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BENEVOLENCE_HELP';
UPDATE Language_en_US SET Text = '-75% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BIG_CITY_PENALTY_HELP';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]can Move and Attack again[ENDCOLOR] after Attack.' WHERE Tag = 'TXT_KEY_PROMOTION_BLITZ_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR]. +50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR]. +50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR]. +50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_4_HELP';
--60
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +20% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +20% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH] Ranged Combat Strength. +20% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP';
UPDATE Language_en_US SET Text = '+40% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_4_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength. +25% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR]. +10% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]from Ranged Attacks[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_CHEST_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_ARROW_RIGHT] Movement Point. +25% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR]. +10% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]from Ranged Attacks[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_HORNS_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength. +50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR]. +15% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]from Ranged Attacks[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_LOINS_HELP';
UPDATE Language_en_US SET Text = '[COLOR_POSITIVE_TEXT]After first Combat[ENDCOLOR] this promotion is replaced with a randomly chosen new special promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_BUSHIDO_HELP';
UPDATE Language_en_US SET Text = 'Unit has more [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on lower Health[ENDCOLOR]. +15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]outside Friendly Territory[ENDCOLOR]. +10 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BUSHIDO_HONOR_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP' WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING';
--70
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP' WHERE Type = 'PROMOTION_CAN_MOVE_IMPASSABLE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY_HELP' WHERE Type = 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FASTER_HEAL_HELP' WHERE Type = 'PROMOTION_FASTER_HEAL';
UPDATE Language_en_US SET Text = 'Double [ICON_ARROW_RIGHT] Movement and +25% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]on Hills, Tundra and Snow[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_I_HELP' WHERE Type = 'PROMOTION_CARGO_I';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_II_HELP' WHERE Type = 'PROMOTION_CARGO_II';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_III_HELP' WHERE Type = 'PROMOTION_CARGO_III';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_IV_HELP' WHERE Type = 'PROMOTION_CARGO_IV';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]in Open Terrain[ENDCOLOR] and +25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]in Open Terrain[ENDCOLOR] and +25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_II_HELP';
--80
UPDATE Language_en_US SET Text = '+150% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT_HELP';
UPDATE Language_en_US SET Text = '-33% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY_HELP';
UPDATE Language_en_US SET Text = '+100% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_HELP';
UPDATE Language_en_US SET Text = '+100% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_II_HELP';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]onto Water Tiles[ENDCOLOR]. Barbarian promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_COAST_WALKER_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. -20% [ICON_RANGE_STRENGTH] Damage Taken [COLOR_POSITIVE_TEXT]from Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. -20% [ICON_RANGE_STRENGTH] Damage Taken [COLOR_POSITIVE_TEXT]from Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]. -20% [ICON_RANGE_STRENGTH] Damage Taken [COLOR_POSITIVE_TEXT]from Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP';
UPDATE Language_en_US SET Text = 'Unit steals [ICON_GOLD] Gold [COLOR_POSITIVE_TEXT]after Attacking the City[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_4_HELP';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]can convert Enemy Unit[ENDCOLOR] to your side [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR]. +100% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COERCION_HELP';
--90
UPDATE Language_en_US SET Text = 'Unit has more [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on lower Health[ENDCOLOR]. +15% [ICON_STRENGTH] Combat Strength. +10 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COURAGE_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]from Ranged Attacks[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COVER_1_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]from Ranged Attacks[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_COVER_2_HELP';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]on Coast-Ocean boundary[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DEEPWATER_EMBARKATION_HELP';
UPDATE Language_en_US SET Text = '+30% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]near Capital[ENDCOLOR]. Bonus is lower if unit gets further away [COLOR_POSITIVE_TEXT]from Capital[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP';
UPDATE Language_en_US SET Text = '-33% [ICON_STRENGTH] Defense Bonus. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP';
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP' WHERE Type = 'PROMOTION_DEFENSE_PENALTY';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]onto Water Tiles[ENDCOLOR]. Double [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is Embarked[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP';
UPDATE Language_en_US SET Text = 'Double [ICON_ARROW_RIGHT] Movement [COLOR_POSITIVE_TEXT]on Desert[ENDCOLOR]. Barbarian promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_DESERT_WALKER_HELP';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Desert[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DESERT_WARRIOR_HELP';
UPDATE Language_en_US SET Text = '+50 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_DIPLOMAT_HELP';
--100
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Air Sweep[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Air Sweep[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP';
UPDATE Language_en_US SET Text = '+34% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Air Sweep[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP';
UPDATE Language_en_US SET Text = '100% of Inflicted City Damage as [ICON_GOLD] Gold [COLOR_POSITIVE_TEXT]after Attacking the City[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DOUBLE_PLUNDER_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength. +25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_1_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength. +25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_2_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength. +25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_3_HELP';
UPDATE Language_en_US SET Text = '+35% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_4_HELP';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]onto Water Tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKATION_HELP';
UPDATE Language_en_US SET Text = '+2 [ICON_VIEW_CITY] Sight [COLOR_POSITIVE_TEXT]on Embark[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP';
--110
UPDATE Language_en_US SET Text = '+30 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_EMISSARY_HELP';
UPDATE Language_en_US SET Text = '50% Heal Chance [COLOR_POSITIVE_TEXT]inside Enemy Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE_HELP';
UPDATE Language_en_US SET Text = 'Unit gains [ICON_PRODUCTION] Production in Capital [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ENSLAVEMENT_HELP';
UPDATE Language_en_US SET Text = '+45 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_ENVOY_HELP';
UPDATE Language_en_US SET Text = '25% Retreat Chance [COLOR_POSITIVE_TEXT]on Enemy Unit after [ICON_RANGE_STRENGTH] Ranged Attack[ENDCOLOR]. +50% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]if Enemy Unit cannot Retreat[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ESPRIT_DE_CORPS_HELP';
UPDATE Language_en_US SET Text = '-50% [ICON_RANGE_STRENGTH] Damage Taken [COLOR_POSITIVE_TEXT]from Interception[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_EVASION_I_HELP' WHERE Type = 'PROMOTION_EVASION_I';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_EVASION_II_HELP' WHERE Type = 'PROMOTION_EVASION_II';
UPDATE Language_en_US SET Text = '+5 HP [COLOR_POSITIVE_TEXT]on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_EVERLASTING_YOUTH_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_STRENGTH] Attack Bonus and +10% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS_HELP';
--120
UPDATE Language_en_US SET Text = '+5 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR] and +1 [ICON_ARROW_RIGHT] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_EXPRESS_HELP';
UPDATE Language_en_US SET Text = 'Unit has [COLOR_POSITIVE_TEXT]bigger Paradrop Range[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_EXTENDED_PARADROP_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_ARROW_RIGHT] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_VIEW_CITY] Sight. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP';
UPDATE Language_en_US SET Text = '+2 [ICON_VIEW_CITY] Sight. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP';
UPDATE Language_en_US SET Text = '+3 [ICON_VIEW_CITY] Sight. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP';
UPDATE Language_en_US SET Text = '+4 [ICON_VIEW_CITY] Sight. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]ignores [ICON_STRENGTH] Fallout Damage[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FALLOUT_IMMUNITY_HELP';
UPDATE Language_en_US SET Text = '[ICON_STRENGTH] Damage Taken [COLOR_POSITIVE_TEXT]from Fallout is reduced[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FALLOUT_REDUCTION_HELP';
UPDATE Language_en_US SET Text = '+2 [ICON_ARROW_RIGHT] Movement Points.' WHERE Tag = 'TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP';
--130
UPDATE Language_en_US SET Text = '+3 [ICON_ARROW_RIGHT] Movement Points.' WHERE Tag = 'TXT_KEY_PROMOTION_FAST_GENERAL_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_ARROW_RIGHT] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_GENERAL_HELP';
UPDATE Language_en_US SET Text = '-10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to every adjacent Enemy Unit[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH]. +10% [ICON_RANGE_STRENGTH] vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FIELD_I_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH]. +10% [ICON_RANGE_STRENGTH] vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FIELD_II_HELP';
UPDATE Language_en_US SET Text = '+5% [ICON_RANGE_STRENGTH]. +10% [ICON_RANGE_STRENGTH] vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FIELD_III_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FIRE_SUPPORT_HELP' WHERE Type = 'PROMOTION_FIRE_SUPPORT';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP' WHERE Type = 'PROMOTION_FLAT_MOVEMENT_COST';
UPDATE Language_en_US SET Text = '+1 Air Unit Slot.' WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_1_HELP';
--140
UPDATE Language_en_US SET Text = '+1 Air Unit Slot.' WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_2_HELP';
UPDATE Language_en_US SET Text = '+1 Air Unit Slot.' WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_3_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FOLIAGE_IMPASSABLE_HELP' WHERE Type = 'PROMOTION_FOLIAGE_IMPASSABLE';
UPDATE Language_en_US SET Text = '+20% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]outside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR], +33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR] and +10% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]in Open Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_1_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR], +33% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Mounted Units[ENDCOLOR] and +10% [ICON_STRENGTH] Defense Bonus [COLOR_POSITIVE_TEXT]in Open Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_2_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FREE_PILLAGE_MOVES_HELP' WHERE Type = 'PROMOTION_FREE_PILLAGE_MOVES';
UPDATE Language_en_US SET Text = '+50% XP [COLOR_POSITIVE_TEXT]on Fight[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is Stacked with Great General[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING_HELP';
UPDATE Language_en_US SET Text = 'Unit gains [ICON_GOLDEN_AGE] Golden Age Points [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS_HELP';
--150
UPDATE Language_en_US SET Text = 'Unit can choose [COLOR_POSITIVE_TEXT]Bonus from Ancient Ruins[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GOODY_HUT_PICKER_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to all Friendly Naval Units within 2 tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP';
UPDATE Language_en_US SET Text = '+70 [ICON_INFLUENCE] Influence from your Civilization and -70 [ICON_INFLUENCE] Influence from others [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Unit gets additional [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]each completed Era[ENDCOLOR]. Unit [COLOR_POSITIVE_TEXT]can Enter Enemy Territory[ENDCOLOR] without Open Borders Agreement. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_DIPLOMAT_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to all Friendly Land Units within 2 tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_GENERAL_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_ARROW_RIGHT] Movement Point and +1 [ICON_VIEW_CITY] Sight.' WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_LIGHTHOUSE_HELP';
UPDATE Language_en_US SET Text = 'Unit gains large amount of [ICON_GOLD] Gold and starts [ICON_HAPPINESS_1] WLTKD [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_MERCHANT_HELP';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on Flanking[ENDCOLOR]. +50% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Wounded Units[ENDCOLOR]. Unit [COLOR_POSITIVE_TEXT]ignores Zone of Control and Terrain Penalties[ENDCOLOR]. +10 HP [COLOR_POSITIVE_TEXT]on Heal inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GUERILLA_FIGHTER_HELP';
UPDATE Language_en_US SET Text = '-10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to every adjacent Enemy Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HAKA_WAR_DANCE_HELP';
UPDATE Language_en_US SET Text = 'Unit Heals all damage [COLOR_POSITIVE_TEXT]on non-Barbarian Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP';
UPDATE Language_en_US SET Text = 'Enemy Unit is forced to Retreat [COLOR_POSITIVE_TEXT]after Attack[ENDCOLOR]. If Enemy Unit cannot Retreat it [COLOR_POSITIVE_TEXT]takes increrased damage[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_CHARGE_HELP';
--160
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HEAVY_PAYLOAD_HELP' WHERE Type = 'PROMOTION_HEAVY_PAYLOAD';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1_HELP' WHERE Type = 'PROMOTION_HELI_AMBUSH_1';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2_HELP' WHERE Type = 'PROMOTION_HELI_AMBUSH_2';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]imitates Great General buffs[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HEROISM_HELP';
UPDATE Language_en_US SET Text = 'Double [ICON_ARROW_RIGHT] Movement [COLOR_POSITIVE_TEXT]on Hill[ENDCOLOR]. Barbarian promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_HILL_WALKER_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_BOOGALOO_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength.' WHERE Tag = 'TXT_KEY_PROMOTION_HONOR_BONUS_HELP';
UPDATE Language_en_US SET Text = 'Unit can Embark [COLOR_POSITIVE_TEXT]onto Water Tiles[ENDCOLOR]. Embarked Unit [COLOR_POSITIVE_TEXT]can Enter Ocean[ENDCOLOR]. +100% [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is Embarked[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HOVER_UNIT_HELP';
--170
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]can Move over Mountain[ENDCOLOR]. If unit [COLOR_POSITIVE_TEXT]ends turn on Mountain[ENDCOLOR] then it takes damage [COLOR_POSITIVE_TEXT]at the beginning of next turn[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_HOVERING_UNIT_HELP';
UPDATE Language_en_US SET Text = 'Unit [COLOR_POSITIVE_TEXT]can Enter Ice[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ICE_BREAKERS_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP' WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';
UPDATE Language_en_US SET Text = '+5 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR]. Unit [COLOR_POSITIVE_TEXT]can Enter Enemy Territory[ENDCOLOR] without Open Borders agreement.' WHERE Tag = 'TXT_KEY_PROMOTION_IMMUNITY_HELP';
UPDATE Language_en_US SET Text = '-10% [ICON_RANGE_STRENGTH] Ranged Combat Strength. Unit [COLOR_POSITIVE_TEXT]can Attack over obstacles[ENDCOLOR] as long as other Friendly Unit can see the target.' WHERE Tag = 'TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP';
UPDATE Language_en_US SET Text = '+50 HP [COLOR_POSITIVE_TEXT]after choosing this promotion[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Interception[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Interception[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2_HELP';
UPDATE Language_en_US SET Text = '+34% [ICON_RANGE_STRENGTH] Ranged Combat Strength [COLOR_POSITIVE_TEXT]on Interception[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INTERCEPTION_I_HELP' WHERE Type = 'PROMOTION_INTERCEPTION_I';
--180
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INTERCEPTION_II_HELP' WHERE Type = 'PROMOTION_INTERCEPTION_II';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INTERCEPTION_III_HELP' WHERE Type = 'PROMOTION_INTERCEPTION_III';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP' WHERE Type = 'PROMOTION_INTERCEPTION_IV';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP' WHERE Type = 'PROMOTION_INVISIBLE_SUBMARINE';
UPDATE Language_en_US SET Text = '+30% [ICON_STRENGTH] Defense Bonus. +20 HP [COLOR_POSITIVE_TEXT]on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_INVULNERABIILITY_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]in Forest and Jungle[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_JAGUAR_HELP';
UPDATE Language_en_US SET Text = '+15 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KILL_HEAL_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Gunpowder Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KNOCKOUT_I_HELP';
UPDATE Language_en_US SET Text = '+25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Siege Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KNOCKOUT_II_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Attack Bonus and +1 [ICON_RIGHT_ARROW] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_HELP';
--190
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Attack Bonus and +1 [ICON_RIGHT_ARROW] Movement Point. Unit [COLOR_POSITIVE_TEXT]ignores Zone of Control[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_ARMOR_HELP';
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Attack Bonus. Unit [COLOR_POSITIVE_TEXT]ignores Zone of Control[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_GUN_HELP';
UPDATE Language_en_US SET Text = '+5 [ICON_INFLUENCE] Influence [COLOR_POSITIVE_TEXT]after Diplomatic Mission[ENDCOLOR] and +1 [ICON_RIGHT_ARROW] Movement Point. Unit [COLOR_POSITIVE_TEXT]ignores Terrain Cost[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LITERACY_HELP';
UPDATE Language_en_US SET Text = 'Unit uses [COLOR_POSITIVE_TEXT]no[ENDCOLOR] [ICON_ARROW_RIGHT] Movement Points [COLOR_POSITIVE_TEXT]on Pillage[ENDCOLOR]. Unit steals [ICON_GOLD] Gold [COLOR_POSITIVE_TEXT]after Attacking the City[ENDCOLOR]. Unit [COLOR_POSITIVE_TEXT]ignores Zone of Control[ENDCOLOR]. -20% [ICON_STRENGTH] Damage Takens [COLOR_POSITIVE_TEXT]from Cities[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LONGBOAT_HELP';
UPDATE Language_en_US SET Text = 'Unit has more [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]on lower Health[ENDCOLOR]. +15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR]. +10 HP [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_LOYALTY_HELP';
UPDATE Language_en_US SET Text = 'Double [ICON_ARROW_RIGHT] Movement [COLOR_POSITIVE_TEXT]on Marsh[ENDCOLOR]. Barbarian promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_MARSH_WALKER_HELP';
UPDATE Language_en_US SET Text = '+5 HP [COLOR_POSITIVE_TEXT]for this and all adjacent Friendly Units on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_HELP';
UPDATE Language_en_US SET Text = '+10 HP [COLOR_POSITIVE_TEXT]for this and all adjacent Friendly Units on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP';
UPDATE Language_en_US SET Text = '+5 HP [COLOR_POSITIVE_TEXT]for this and all adjacent Friendly Units on Heal[ENDCOLOR]. +5 HP [COLOR_POSITIVE_TEXT]on Heal inside Enemy Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_II_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_RIGHT_ARROW] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_HELP';
--200
UPDATE Language_en_US SET Text = '-50% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Fortified Units and Cities[ENDCOLOR]. -25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR]. +20% [ICON_STRENGTH] Defense Bonus. -15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to Enemy Units within 2 tiles[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_MODERN_RANGED_PENALTY_I_HELP';
UPDATE Language_en_US SET Text = '-25% [ICON_RANGE_STRENGTH] Ranged Combat Strength vs [COLOR_POSITIVE_TEXT]Fortified Units and Cities[ENDCOLOR]. +10% [ICON_STRENGTH] Defense Bonus. -10% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]to Enemy Units within 2 tiles[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_MODERN_RANGED_PENALTY_II_HELP';
UPDATE Language_en_US SET Text = '+33% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]in Forest and Jungle[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK_HELP';
UPDATE Language_en_US SET Text = '+2 [ICON_RIGHT_ARROW] Movement Point. Unit [COLOR_POSITIVE_TEXT]ignores Zone of Control[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MONGOL_TERROR_HELP';
UPDATE Language_en_US SET Text = '+1 [ICON_RIGHT_ARROW] Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_MOON_STRIKER_HELP';
UPDATE Language_en_US SET Text = '+10% [ICON_STRENGTH] Combat Strength.' WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MOUNTED_PENALTY_HELP' WHERE Type = 'PROMOTION_MOUNTED_PENALTY';
UPDATE Language_en_US SET Text = '[COLOR_POSITIVE_TEXT]At the beginning of the turn[ENDCOLOR] if Great General [COLOR_POSITIVE_TEXT]is stacked with a Friendly Unit[ENDCOLOR] with this promotion, he gets same amount of [ICON_ARROW_RIGHT] Movement Points as this unit.' WHERE Tag = 'TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MUST_SET_UP_HELP' WHERE Type = 'PROMOTION_MUST_SET_UP';
UPDATE Language_en_US SET Text = '[COLOR_POSITIVE_TEXT]After first Combat[ENDCOLOR] this promotion is replaced with a randomly chosen new special promotion.' WHERE Tag = 'TXT_KEY_PROMOTION_MYSTIC_BLADE_HELP';
--210
UPDATE Language_en_US SET Text = '+15% [ICON_STRENGTH] Attack Bonus [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_NATIONALISM_HELP';
UPDATE Language_en_US SET Text = '+50% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Naval Units, but not Carriers and Submarines[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_BONUS_HELP';
UPDATE Language_en_US SET Text = '+20% [ICON_STRENGTH] Defense Bonus.' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_DEFENSE_BOOST_HELP';
UPDATE Language_en_US SET Text = '-25% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_INACCURACY_HELP';
UPDATE Language_en_US SET Text = '-20% [ICON_STRENGTH] Combat Strength vs [COLOR_POSITIVE_TEXT]Naval Units[ENDCOLOR]. Lost after unit upgrade.' WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_MISFIRE_HELP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_NAVAL_PENALTY_HELP' WHERE Type = 'PROMOTION_NAVAL_PENALTY';

/*
UPDATE Language_en_US SET Text = '' WHERE Tag = '';
UPDATE UnitPromotions SET Help = '' WHERE Type = '';
*/