/*
AT compatibility patch!
0 = Disabled disregarding if its detects AT by adan_eslavo.
1 = Enabled if it detects the AT by adan_eslavo.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('PO-AT', 		2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'PO-AT' AND EXISTS (SELECT * FROM UnitPromotions WHERE Type='PROMOTION_CANOE') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 0);

-- Main Compatibility Code
	-- updating texts for new promotions
	------------------------------
	-- Promotion Names
	------------------------------
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Canoe[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_CANOE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Floater[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_FLOATER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Unstoppable[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNSTOPPABLE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Trailblazer[ENDCOLOR]' WHERE Tag ='TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Wayfarer[ENDCOLOR]' WHERE Tag ='TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Voyager[ENDCOLOR]' WHERE Tag ='TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);

	------------------------------
	-- Promotion Help
	------------------------------
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can Embark[ENDCOLOR]. +1[ICON_MOVES]Movement Point and +25%[ICON_STRENGTH]Defensive CS if unit [COLOR:255:230:85:255]is Embarked[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_CANOE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Double[ICON_MOVES]Movement and Heal, and +10%[ICON_STRENGTH]Defensive CS [COLOR:255:230:85:255]in Marsh, Oasis or Flood Plains[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FLOATER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]ignores Zone of Control[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_UNSTOPPABLE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);

	UPDATE Language_en_US SET Text = REPLACE(Text, ' Requires [ICON_RESEARCH][COLOR_RESEARCH_STORED]Railroad[ENDCOLOR].', '') WHERE Tag ='TXT_KEY_PROMOTION_FROGMAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = REPLACE(Text, ' Unit [COLOR:255:230:85:255]ignores Zone of Control[ENDCOLOR].', '') WHERE Tag ='TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = REPLACE(Text, 'Embark, ', '') WHERE Tag ='TXT_KEY_PROMOTION_WOODLAND_TRAILBLAZER_3_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);

	UPDATE Language_en_US SET Text = '+1[ICON_MOVES]Movement Point.' WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = '+1 [ICON_VP_VISION] Sight.' WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_3_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);
	UPDATE Language_en_US SET Text = Text||' +10%[ICON_STRENGTH]CS [COLOR:255:230:85:255]outside Friendly Territory[ENDCOLOR].' WHERE Tag IN ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', 'TXT_KEY_PROMOTION_SCOUTING_3_HELP') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-AT' AND Value= 1);