/*
Custom Civilizations compatibility patches!
0 = Disabled disregarding if its detects new custom civilizations.
1 = Enabled if it detects new custom civilizations.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,								Value)
VALUES	('PO-CIVILIZATION-CAMBODIA', 		2), -- @pineappledan's part
		('PO-CIVILIZATION-CANADA', 			2),
		('PO-CIVILIZATION-CHOLA', 			2),
		('PO-CIVILIZATION-GOTHS', 			2),
		('PO-CIVILIZATION-INUIT', 			2),
		('PO-CIVILIZATION-ISRAEL', 			2),
		('PO-CIVILIZATION-MACEDON', 		2),
		('PO-CIVILIZATION-NUBIA', 			2),
		('PO-CIVILIZATION-PHILIPINES', 		2),
		('PO-CIVILIZATION-PHOENICIA', 		2),
		('PO-CIVILIZATION-SUMER', 			2),
		('PO-CIVILIZATION-TIMURIDS', 		2),
		('PO-CIVILIZATION-TLINGIT', 		2),

		('PO-CIVILIZATION-AINU', 			2), -- @gwennog's part
		('PO-CIVILIZATION-BASQUE', 			2),
		('PO-CIVILIZATION-CORSICA', 		2),
		('PO-CIVILIZATION-IRELAND', 		2),
		('PO-CIVILIZATION-KYIVIAN-RUS', 	2),
		('PO-CIVILIZATION-LOUISIANA', 		2);

UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CAMBODIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_KHMER') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CAMBODIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CANADA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_COLONIALCANADA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CANADA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CHOLA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_VP_CHOLA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CHOLA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-GOTHS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_VISIGOTHS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-GOTHS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-INUIT' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_CLINUIT') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-INUIT' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-ISRAEL' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_LEUGI_ISRAEL') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-ISRAEL' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-MACEDON' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_MC_MACEDON') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-MACEDON' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-NUBIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_MC_LITE_NUBIA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-NUBIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-PHILIPINES' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_JFD_PHILIPPINES') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-PHILIPINES' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-PHOENICIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_PHOENICIA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-PHOENICIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-SUMER' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AKKADIAN_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-SUMER' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-TIMURIDS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_TIMURIDS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-TIMURIDS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-TLINGIT' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_CL_TLINGIT') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-TLINGIT' AND Value=0);

UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-AINU' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_HININ_AINU') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-BASQUE' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_GT_BASQUES') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CORSICA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_DMS_CORSICA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-IRELAND' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_JFD_IRELAND_BRIAN_BORU') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-KYIVIAN-RUS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_KIEVAN_RUS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-LOUISIANA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_GH_LOUISIANA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value=0);

-- Main Compatibility Code
	-- updating texts for new promotions
	------------------------------
	-- Promotion Names
	------------------------------
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kerep-Noye[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Wither[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_WITHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Prowl[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_PROWL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Foundation[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_FOUNDATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Track[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRACK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Ambushed[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_AMBUSHED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Soul Liberation[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SOUL_LIBERATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Guidance[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_GUIDANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Spirited[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SPIRITED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Trapped[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRAPPED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Babesten[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_BABESTEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Lema[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_CULTURE_BOMB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Arrantza-eremu Berriak[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_DISCOVER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Merkataritzaren Izenean[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MERKATARITZAREN_IZENEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marque Gutuna[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MARQUE_GUTUNA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kortsarioa[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_KORTSARIOA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Maquisard[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hide in Maquis[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_EFFECT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Torrean[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_TORREAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marauder[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MARAUDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Across all Boundaries[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_NEWCOMER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Lia Fáil[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_LIA_FAIL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Dord Fian[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_THP_FIANN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Dá apstol décc na hÉrenn[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_DA_APSTOL_DECC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]An Bradán Feasa[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_AN_BRADAN_FEASA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Breitheamh[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_BREITHEAMH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Zakhysnyk[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Knyazhyy radnyk[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hetman Guard[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_KYIVAN_HETMAN_GUARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Zaporizhian Osaul[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ZAPOSAUL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	--UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255][ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ESPRIT_DE_CORPS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Engagés[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENGAGES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Interpr?te[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INTERPRETE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Petite Guerre[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_PETITE_GUERRE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Entrepreneur[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENTREPRENEUR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Métissage[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_METISSAGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Indigenous Allies[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INDIGENOUS_ALLIES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Guide and Pemmican[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_GUIDE_AND_PEMMICAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Mardi Gras[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_KREWE_MARDIGRAS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	
	------------------------------
	-- Promotion Help
	------------------------------
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_WITHER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_PROWL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_FOUNDATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRACK_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_AMBUSHED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SOUL_LIBERATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_GUIDANCE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SPIRITED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRAPPED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_BABESTEN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_CULTURE_BOMB_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_DISCOVER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MERKATARITZAREN_IZENEAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MARQUE_GUTUNA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_KORTSARIOA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_EFFECT_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_TORREAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MARAUDER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_NEWCOMER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_LIA_FAIL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_THP_FIANN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_DA_APSTOL_DECC_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_AN_BRADAN_FEASA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_BREITHEAMH_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_KYIVAN_HETMAN_GUARD_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_ZAPOSAUL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	--UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_ESPRIT_DE_CORPS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENGAGES_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INTERPRETE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_PETITE_GUERRE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENTREPRENEUR_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_METISSAGE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INDIGENOUS_ALLIES_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_GUIDE_AND_PEMMICAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_KREWE_MARDIGRAS_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	