/*
Custom Civilizations compatibility patches!
0 = Disabled disregarding if its detects new custom civilizations.
1 = Enabled if it detects new custom civilizations.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,								Value)
VALUES	('PO-CIVILIZATION-CAMBODIA', 		2), -- @pineappledan's part
		('PO-CIVILIZATION-CANADA', 			2),
		('PO-CIVILIZATION-CHOLA', 			2),
		('PO-CIVILIZATION-GOTHS', 			2),
		('PO-CIVILIZATION-INUIT', 			2),
		('PO-CIVILIZATION-ISRAEL', 			2),
		('PO-CIVILIZATION-MACEDON', 		2),
		('PO-CIVILIZATION-NUBIA', 			2),
		('PO-CIVILIZATION-PHILIPINES', 		2),
		('PO-CIVILIZATION-PHOENICIA', 		2),
		('PO-CIVILIZATION-SUMER', 			2),
		('PO-CIVILIZATION-TIMURIDS', 		2),
		('PO-CIVILIZATION-TLINGIT', 		2),

		('PO-CIVILIZATION-AINU', 			2), -- @gwennog's part
		('PO-CIVILIZATION-BASQUE', 			2),
		('PO-CIVILIZATION-CORSICA', 		2),
		('PO-CIVILIZATION-IRELAND', 		2),
		('PO-CIVILIZATION-KYIVIAN-RUS', 	2),
		('PO-CIVILIZATION-LOUISIANA', 		2);

UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CAMBODIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_KHMER') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CAMBODIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CANADA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_COLONIALCANADA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CANADA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CHOLA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_VP_CHOLA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CHOLA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-GOTHS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_VISIGOTHS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-GOTHS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-INUIT' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_CLINUIT') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-INUIT' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-ISRAEL' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_LEUGI_ISRAEL') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-ISRAEL' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-MACEDON' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_MC_MACEDON') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-MACEDON' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-NUBIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_MC_LITE_NUBIA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-NUBIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-PHILIPINES' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_JFD_PHILIPPINES') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-PHILIPINES' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-PHOENICIA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_PHOENICIA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-PHOENICIA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-SUMER' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AKKADIAN_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-SUMER' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-TIMURIDS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_TIMURIDS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-TIMURIDS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-TLINGIT' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_CL_TLINGIT') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-TLINGIT' AND Value=0);

UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-AINU' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_HININ_AINU') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-BASQUE' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_GT_BASQUES') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-CORSICA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_DMS_CORSICA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-IRELAND' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_JFD_IRELAND_BRIAN_BORU') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-KYIVIAN-RUS' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_KIEVAN_RUS_MOD') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value=0);
UPDATE Community SET Value = '1' WHERE Type = 'PO-CIVILIZATION-LOUISIANA' AND EXISTS (SELECT * FROM Civilizations WHERE Type='CIVILIZATION_GH_LOUISIANA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value=0);

-- Main Compatibility Code
	-- updating texts for new promotions
	------------------------------
	-- Promotion Names
	------------------------------
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kerep-Noye[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Wither[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_WITHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Prowl[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_PROWL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Foundation[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_FOUNDATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Track[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRACK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Ambushed[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_AMBUSHED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Soul Liberation[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SOUL_LIBERATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Guidance[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_GUIDANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Spirited[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SPIRITED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Trapped[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRAPPED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Babesten[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_BABESTEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Lema[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_CULTURE_BOMB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Arrantza-eremu Berriak[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_DISCOVER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Merkataritzaren Izenean[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MERKATARITZAREN_IZENEAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marque Gutuna[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MARQUE_GUTUNA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kortsarioa[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_KORTSARIOA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Maquisard[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hidden in Maquis[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_EFFECT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Torrean[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_TORREAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marauder[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MARAUDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Across all Boundaries[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_NEWCOMER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Lia Fáil[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_LIA_FAIL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:190:180:45:255]Dord Fian[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_THP_FIANN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Dá apstol décc na hÉrenn[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_DA_APSTOL_DECC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]An Bradán Feasa[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_AN_BRADAN_FEASA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Breitheamh[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_BREITHEAMH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Zakhysnyk[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Knyazhyy radnyk[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hetman Guard[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_KYIVAN_HETMAN_GUARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Zaporizhian Osaul[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ZAPOSAUL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	--UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255][ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ESPRIT_DE_CORPS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Engagés[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENGAGES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Interprète[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INTERPRETE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Petite Guerre[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_PETITE_GUERRE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Entrepreneur[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENTREPRENEUR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Métissage[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_METISSAGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Indigenous Allies[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INDIGENOUS_ALLIES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Guide and Pemmican[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_GUIDE_AND_PEMMICAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Mardi Gras[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_KREWE_MARDIGRAS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	
	------------------------------
	-- Promotion Help
	------------------------------
	UPDATE Language_en_US SET Text = '[COLOR:255:230:85:255]After Attack[ENDCOLOR] Defending Enemy Unit gains [COLOR:250:100:100:255]Wither[ENDCOLOR] promotion, which [COLOR:255:230:85:255]reduces its healing from Fortifying/Waiting by 10 HP[ENDCOLOR] for 2 turns.' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '-10 HP Heal [COLOR:250:100:100:255]on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_WITHER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]ignores Zone of Control[ENDCOLOR]. +100%[ICON_ARROW_LEFT]Withdrawal Chance [COLOR:255:230:85:255]vs Melee Attack[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_PROWL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);	
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can build Camps, Fishing Boats and Kotans[ENDCOLOR]. At level 4, unit [COLOR:255:230:85:255]can be upgraded to Composite Bowman or expended to found a City[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_FOUNDATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:255:230:85:255]After Attack[ENDCOLOR] Defending Enemy Unit gains [COLOR:250:100:100:255]Ambushed[ENDCOLOR] promotion, which [COLOR:255:230:85:255]negates defensive bonuses from terrains and features[ENDCOLOR] for 2 turns.' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRACK_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:250:100:100:255]gains no defensive bonuses from terrains and features[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_AMBUSHED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can Attack again[ENDCOLOR], and gains 5 XP and +1[ICON_MOVES]Movement Point [COLOR:255:230:85:255]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SOUL_LIBERATION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:255:230:85:255]If Alive[ENDCOLOR], unit [COLOR:255:230:85:255]provides -7% [ICON_HAPPINESS_3] Need Modifers on Empire[ENDCOLOR] (caps at -20%). Grants [COLOR:100:155:60:255]Spirited[ENDCOLOR] promotion [COLOR:255:230:85:255]to all Friendly Land Units within 1 tile[ENDCOLOR] for 2 turns.' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_GUIDANCE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '-3 Damage Taken.' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_SPIRITED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE Language_en_US SET Text = '-1[ICON_MOVES]Movement Point and -10%[ICON_STRENGTH]Attacking CS [COLOR:250:100:100:255]on Flanking[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HININ_AINU_TRAPPED_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '+1[ICON_MOVES]Movement Point. Unit [COLOR:255:230:85:255]can Enter Mountain[ENDCOLOR]. Occupied Basque Cities can spawn Partisans during a War.' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_BABESTEN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]ignores Zone of Control[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_CULTURE_BOMB_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_RESEARCH] and [ICON_GREAT_ADMIRAL] [COLOR:255:230:85:255]for revealing tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_DISCOVER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '30 [ICON_INFLUENCE] Influence with all [ICON_CITY_STATE] Maritime City-States (at [ICON_PEACE] Peace) [COLOR:255:230:85:255]when Expended[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MERKATARITZAREN_IZENEAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Grants [COLOR:100:155:60:255]Kortsarioa[ENDCOLOR] promotion [COLOR:255:230:85:255]to all Friendly Military Naval Units within 2 tiles[ENDCOLOR] for 5 turns.' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_MARQUE_GUTUNA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE Language_en_US SET Text = '+1 [ICON_VP_VISION] Sight. Unit [COLOR:255:230:85:255]can Enter Enemy Territory without Open Borders Agreement[ENDCOLOR] and [COLOR:255:230:85:255]can Heal outside Friendly Territory[ENDCOLOR]. Unit gains 1 XP, [ICON_GOLD] and [ICON_CULTURE], if it [COLOR:255:230:85:255]is on or adjacent to [ICON_CARAVAN] Land or [ICON_CARGO_SHIP] Sea Trade Route of another Player[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GT_BASQUES_KORTSARIOA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	
	UPDATE Language_en_US SET Text = 'Unit gains [COLOR:100:155:60:255]Hidden in the Maquis[ENDCOLOR] promotion, if it [COLOR:255:230:85:255]starts its turn in Rough Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can Move again[ENDCOLOR] after Attack. [COLOR:255:230:85:255]At the beginning of each turn[ENDCOLOR] unit inflicts 15 Damage [COLOR:255:230:85:255]to all adjacent Enemy Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MAQUISARD_EFFECT_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '+25%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]if Unit starts its turn next to a City[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_TORREAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]ignores Terrain Cost[ENDCOLOR]. Unit gains 5 XP [COLOR:255:230:85:255]on Kill[ENDCOLOR], 3 XP [COLOR:255:230:85:255]when Pillaging the tile[ENDCOLOR] and 10 XP [COLOR:255:230:85:255]when Pillaging the [ICON_INTERNATIONAL_TRADE] Trade Route[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_MARAUDER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	UPDATE Language_en_US SET Text = '+1 [ICON_VP_VISION] Sight. Unit [COLOR:255:230:85:255]can Embark[ENDCOLOR]. Unit [COLOR:255:230:85:255]can Enter Mountain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_CORSICA_NEWCOMER_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-CORSICA' AND Value= 1);
	
	UPDATE Language_en_US SET Text = 'Unit generates [ICON_GREAT_WRITER] in the [ICON_CAPITAL] Capital [COLOR:255:230:85:255]on Promotion or Upgrade[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_LIA_FAIL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit generates [ICON_GREAT_WRITER] in the [ICON_CAPITAL] Capital [COLOR:255:230:85:255]on Pillage[ENDCOLOR] (more, if the tile contains a Resource). Unit [COLOR:250:100:100:255]cannot Pillage Roads or Railroads[ENDCOLOR], but it [COLOR:255:230:85:255]can use enemy Roads and Railroads[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_THP_FIANN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '+2[ICON_MOVES]Movement Points.' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_DA_APSTOL_DECC_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '+2 [ICON_GREAT_MUSICIAN] to all [ICON_GREAT_WORK] Great Works of Writing.' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_AN_BRADAN_FEASA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	UPDATE Language_en_US SET Text = '-1 [ICON_HAPPINESS_3] Distress, -1 [ICON_HAPPINESS_3] Boredom and +20% [ICON_PEACE] Conversion Resistance in all Cities for 15 turns [COLOR:255:230:85:255]when Expended[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_UNITY_IRELAND_BREITHEAMH_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-IRELAND' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '+1 [ICON_VP_VISION] Sight. +20%[ICON_STRENGTH]CS if unit [COLOR:255:230:85:255]is within 2 tiles from a Great Person or Great Person Tile Improvement[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit generates [ICON_DIPLOMAT] in the [ICON_CAPITAL] Capital [COLOR:255:230:85:255]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_JAR_DRUZHINA2_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = '+20%[ICON_STRENGTH]Defensive CS/[ICON_RANGE_STRENGTH]Defensive RCS [COLOR:255:230:85:255]for all adjacent Friendly Land Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KYIVAN_HETMAN_GUARD_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit uses [COLOR:255:230:85:255]no[ENDCOLOR][ICON_MOVES]Movement Points [COLOR:255:230:85:255]on Pillage[ENDCOLOR]. Unit uses 1[ICON_MOVES]Movement Point [COLOR:255:230:85:255]to Cross a River[ENDCOLOR]. Unit gains [ICON_GOLD], if it [COLOR:255:230:85:255]is inside Enemy Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ZAPOSAUL_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	--UPDATE Language_en_US SET Text = '' WHERE Tag = 'TXT_KEY_PROMOTION_ESPRIT_DE_CORPS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	
	UPDATE Language_en_US SET Text = '+1 [ICON_VP_VISION] Sight. +5 HP Heal [COLOR:255:230:85:255]for all adjacent Friendly Units on Heal[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENGAGES_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '+1[ICON_MOVES]Movement Point. +35%[ICON_STRENGTH]CS [COLOR:255:230:85:255]vs Barbarians[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INTERPRETE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '+15 HP. +10%[ICON_STRENGTH]CS [COLOR:255:230:85:255]for all Friendly Military Units within 2 tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_PETITE_GUERRE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit generates [ICON_GREAT_MERCHANT] in the [ICON_CAPITAL] Capital each turn.' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_ENTREPRENEUR_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit generates [ICON_GREAT_WRITER] in the [ICON_CAPITAL] Capital [COLOR:255:230:85:255]for revealing tiles or on Promotion[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_METISSAGE_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:255:230:85:255]When [ICON_GREAT_MERCHANT] Great Merchant is Expended[ENDCOLOR], all units on the same landmass as this unit gain [COLOR:100:155:60:255]Guide and Pemmican[ENDCOLOR] promotion for 10 turns.' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_INDIGENOUS_ALLIES_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]ignores Terrain Cost[ENDCOLOR]. Unit [COLOR:255:230:85:255]is immune to Land Plagues[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_GUIDE_AND_PEMMICAN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:255:230:85:255]When Expended[ENDCOLOR], all Buildings with slots for [ICON_GREAT_WORK] Great Work of Music, or [ICON_GREAT_MERCHANT] Merchant, [ICON_GREAT_MUSICIAN] Musician or [ICON_DIPLOMAT] Diplomat Specialist gain +1 [ICON_TOURISM] for 15 turns. Unit starts [ICON_HAPPINESS_1] WLTKD in all Cities, [COLOR:255:230:85:255]when Expended in Friendly Territory[ENDCOLOR]. Unit starts [ICON_RESISTANCE] in nearest Enemy City, [COLOR:255:230:85:255]when Expended in Rival Territory[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_GH_LOUISIANA_KREWE_MARDIGRAS_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-LOUISIANA' AND Value= 1);
	
	------------------------------
	-- Promotion New Help Texts
	------------------------------
	INSERT INTO Language_en_US
				(Tag,													Text)
	SELECT		'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE_M_HELP',		'[COLOR:255:230:85:255]After Attack[ENDCOLOR] Defending Enemy Unit gains [COLOR:250:100:100:255]Wither[ENDCOLOR] promotion, which [COLOR:255:230:85:255]reduces its healing from Fortifying/Waiting by 10 HP[ENDCOLOR] for 2 turns.' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1) UNION ALL
	SELECT		'TXT_KEY_PROMOTION_KYIVAN_WITHERING_FIRE_HELP',			'+25%[ICON_ARROW_LEFT]Retreat Chance [COLOR:255:230:85:255]on Enemy Unit[ENDCOLOR] after Ranged Attack. +50%[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]if Enemy Unit cannot Retreat[ENDCOLOR].' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HININ_AINU_KEREPNOYE_M_HELP' WHERE Type = 'PROMOTION_HININ_AINU_KEREPNOYE_M' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-AINU' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_KYIVAN_WITHERING_FIRE_HELP' WHERE Type = 'PROMOTION_KYIVAN_WITHERING_FIRE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);

	------------------------------
	-- Promotion Pedia
	------------------------------
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_GT_BASQUES_BABESTEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_MOUNTED' WHERE Type = 'PROMOTION_ZAPOSAUL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-KYIVIAN-RUS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_UNITY_IRELAND_LIA_FAIL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-CIVILIZATION-BASQUE' AND Value= 1);