--=============================================--
-- MW compatibility check
--=============================================--
/* More Wonders */
INSERT INTO BuildingClasses (Type)
SELECT		'BUILDINGCLASS_DUMMY_PO_MW'
WHERE EXISTS (SELECT * FROM UnitPromotions WHERE Type='PROMOTION_MARAE');

CREATE TRIGGER IF NOT EXISTS POCompatibilityMW
AFTER INSERT ON UnitPromotions
WHEN NEW.Type = 'PROMOTION_MARAE'
BEGIN
    INSERT INTO BuildingClasses (Type)
	VALUES		('BUILDINGCLASS_DUMMY_PO_MW');
END;

--=============================================--
-- MW compatibility changes
--=============================================--
	------------------------------
	-- Promotion Names
	------------------------------
	-- World Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marae[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MARAE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Arahurahu[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ARAHURAHU' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Damascus Steel[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DAMASCUS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hidden Artifacts[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HIDDEN_ARTIFACTS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Panama Canal[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_PANAMA_CANAL' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Toy Train[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DARJEELING' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze: For the Emperor![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_EFFECT' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Fleet of the Sun[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_SEA' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Imperial Army[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_LAND' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]White Sands Facility[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_WHITE_SANDS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Trans-Siberian Railway[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SIBERIAN_RAILWAY' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Operational Range[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_THULE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	
	-- Buildings
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Yerba de la Fleche[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_FLETCHER' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	
	-- Natural Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Mahaprasthanika Parva[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_KAILASH' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Old Tribes[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ULURU' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]For the King![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SOLOMONS_MINES' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Explosive Mixture[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DALLOL' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Curiosity[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_CAUSEWAY' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Roof of the World[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MT_EVEREST' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Revontulet[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_AURORA' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');

	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Lost in Time and Space[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	------------------------------
	-- Promotion Help
	------------------------------
	UPDATE Language_en_US SET Text = '+1 [ICON_VISION] Sight. Double[ICON_MOVES]Movement and +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');