--=============================================--
-- MW compatibility check (part I)
--=============================================--
/* More Wonders */
INSERT INTO BuildingClasses (Type)
SELECT		'BUILDINGCLASS_DUMMY_PO_MW'
WHERE EXISTS (SELECT * FROM UnitPromotions WHERE Type='PROMOTION_MARAE');
--=============================================--
-- MW compatibility changes
--=============================================--
	------------------------------
	-- Promotion Names
	------------------------------
	-- World Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marae[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MARAE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Arahurahu[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ARAHURAHU' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Damascus Steel[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DAMASCUS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hidden Artifacts[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HIDDEN_ARTIFACTS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Panama Canal[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_PANAMA_CANAL' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Toy Train[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DARJEELING' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze: For the Emperor![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_EFFECT' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Fleet of the Sun[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_SEA' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Imperial Army[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_LAND' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]White Sands Facility[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_WHITE_SANDS' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Trans-Siberian Railway[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SIBERIAN_RAILWAY' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Operational Range[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_THULE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Vexillum Hospitalorum[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HOSPITALLER' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Tuitio Fidei[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_TUITIO_FIDEI' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	
	-- Buildings
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Yerba de la Fleche[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_FLETCHER' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	
	-- Natural Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Mahaprasthanika Parva[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_KAILASH' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Old Tribes[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ULURU' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]For the King![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SOLOMONS_MINES' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Explosive Mixture[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DALLOL' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Curiosity[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_CAUSEWAY' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Roof of the World[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MT_EVEREST' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Descending Dragon[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HA_LONG' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Revontulet[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_AURORA' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);

	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Lost in Time and Space[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW') AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-SETTING-TITLE' AND Value= 1);
	------------------------------
	-- Promotion Help
	------------------------------
	-- World Wonders
	UPDATE Language_en_US SET Text = '+10%[ICON_RANGE_STRENGTH]RCS.' WHERE Tag = 'TXT_KEY_PROMOTION_MARAE_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_CULTURE] [COLOR:255:230:85:255]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ARAHURAHU_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+10%[ICON_STRENGTH]CS.' WHERE Tag = 'TXT_KEY_PROMOTION_DAMASCUS_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+20% [ICON_WORKER] Work Rate. Unit [COLOR:255:230:85:255]can Enter (cannot Dig on) Enemy Territory without Open Borders Agreement[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HIDDEN_ARTIFACTS_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+1[ICON_ARROW_RIGHT]Movement Point. +10 HP Heal [COLOR:255:230:85:255]on Heal inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_PANAMA_CANAL_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can Enter Mountain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DARJEELING_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+30%[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]has 20% of its maximum HP or less[ENDCOLOR] [COLOR_GREY](inactive)[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+30%[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]has 20% of its maximum HP or less[ENDCOLOR] [COLOR_POSITIVE_TEXT](active)[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_EFFECT_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Unit deals Damage [COLOR:255:230:85:255]to attackng Air Unit[ENDCOLOR] (not available on Submarines). Requires [ICON_RESEARCH][COLOR_RESEARCH_STORED]Flight[ENDCOLOR]. +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]is adjacent to another Friendly Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_SEA_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Bonus[ICON_MOVES]Movement Point [COLOR:255:230:85:255]after crossing Rivers[ENDCOLOR]. +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]in Rough Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_LAND_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+2 [ICON_SWAP] Range.' WHERE Tag = 'TXT_KEY_PROMOTION_WHITE_SANDS_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Double [ICON_MOVES]Movement [COLOR:255:230:85:255]on Tundra and Snow[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SIBERIAN_RAILWAY_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+5%[ICON_RANGE_STRENGTH]Offensive RCS. +2 [ICON_SWAP] Range.' WHERE Tag = 'TXT_KEY_PROMOTION_THULE_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+5 HP Heal [COLOR:255:230:85:255]on Heal inside Enemy Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HOSPITALLER_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+35%[ICON_STRENGTH]CS [COLOR:255:230:85:255]vs Mounted Units[ENDCOLOR]. Unit generates 15% [ICON_FOOD], if it [COLOR:255:230:85:255]is Garrisoned[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_TUITIO_FIDEI_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');

	-- Buildings
	UPDATE Language_en_US SET Text = '+50%[ICON_STRENGTH]Offensive CS/[ICON_RANGE_STRENGTH]Offensive RCS [COLOR:255:230:85:255]vs Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FLETCHER_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');

	-- Natural Wonders
	UPDATE Language_en_US SET Text = 'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KAILASH_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+10 [ICON_INFLUENCE] Influence [COLOR:255:230:85:255]after Diplomatic Mission[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ULURU_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+25% [ICON_WORKER] Work Rate.' WHERE Tag = 'TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+10%[ICON_RANGE_STRENGTH]Offensive RCS.' WHERE Tag = 'TXT_KEY_PROMOTION_DALLOL_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = '+1[ICON_MOVES]Movement Point. +20% [ICON_WORKER] Work Rate.' WHERE Tag = 'TXT_KEY_PROMOTION_CAUSEWAY_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_TOURISM] [COLOR:255:230:85:255]for revealing tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MT_EVEREST_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_CULTURE] [COLOR:255:230:85:255]on Kill[ENDCOLOR]. +20%[ICON_STRENGTH]Defensive CS.' WHERE Tag = 'TXT_KEY_PROMOTION_HA_LONG_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	UPDATE Language_en_US SET Text = 'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Snow[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AURORA_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');

	UPDATE Language_en_US SET Text = '-3[ICON_MOVES]Movement Points. [COLOR_NEGATIVE_TEXT]Promotion lasts 3 turns[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
	
	UPDATE Language_en_US SET Text = '+1 [ICON_VISION] Sight. Double[ICON_MOVES]Movement and +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP' AND EXISTS (SELECT * FROM BuildingClasses WHERE Type='BUILDINGCLASS_DUMMY_PO_MW');
--=============================================--
-- MW compatibility trigger (part II)
--=============================================--
/* More Wonders */
CREATE TRIGGER IF NOT EXISTS POCompatibilityMW
AFTER INSERT ON UnitPromotions
WHEN NEW.Type = 'PROMOTION_MARAE'
BEGIN
    INSERT INTO BuildingClasses (Type)
	VALUES		('BUILDINGCLASS_DUMMY_PO_MW_TRG');
	
	------------------------------
	-- Promotion Names
	------------------------------
	-- World Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Marae[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MARAE';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Arahurahu[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ARAHURAHU';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Damascus Steel[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DAMASCUS';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Hidden Artifacts[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HIDDEN_ARTIFACTS';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Panama Canal[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_PANAMA_CANAL';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Toy Train[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DARJEELING';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Kamikaze: For the Emperor![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_EFFECT';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Fleet of the Sun[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_SEA';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Imperial Army[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_LAND';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]White Sands Facility[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_WHITE_SANDS';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Trans-Siberian Railway[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SIBERIAN_RAILWAY';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Operational Range[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_THULE';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Vexillum Hospitalorum[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_HOSPITALLER';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Tuitio Fidei[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_TUITIO_FIDEI';

	-- Buildings
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Yerba de la Fleche[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_FLETCHER';
	
	-- Natural Wonders
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Mahaprasthanika Parva[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_KAILASH';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Old Tribes[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_ULURU';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]For the King![ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_SOLOMONS_MINES';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Explosive Mixture[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_DALLOL';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Curiosity[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_CAUSEWAY';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Roof of the World[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_MT_EVEREST';
	UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Revontulet[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_AURORA';

	UPDATE Language_en_US SET Text = '[COLOR:250:100:100:255]Lost in Time and Space[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE';
	------------------------------
	-- Promotion Help
	------------------------------
	-- World Wonders
	UPDATE Language_en_US SET Text = '+10%[ICON_RANGE_STRENGTH]RCS.' WHERE Tag = 'TXT_KEY_PROMOTION_MARAE_HELP';
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_CULTURE] [COLOR:255:230:85:255]on Kill[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ARAHURAHU_HELP';
	UPDATE Language_en_US SET Text = '+10%[ICON_STRENGTH]CS.' WHERE Tag = 'TXT_KEY_PROMOTION_DAMASCUS_HELP';
	UPDATE Language_en_US SET Text = '+20% [ICON_WORKER] Work Rate. Unit [COLOR:255:230:85:255]can Enter (cannot Dig on) Enemy Territory without Open Borders Agreement[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HIDDEN_ARTIFACTS_HELP';
	UPDATE Language_en_US SET Text = '+1[ICON_ARROW_RIGHT]Movement Point. +10 HP Heal [COLOR:255:230:85:255]on Heal inside Friendly Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_PANAMA_CANAL_HELP';
	UPDATE Language_en_US SET Text = 'Unit [COLOR:255:230:85:255]can Enter Mountain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_DARJEELING_HELP';
	UPDATE Language_en_US SET Text = '+30%[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]has 20% of its maximum HP or less[ENDCOLOR] [COLOR_GREY](inactive)[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_HELP';
	UPDATE Language_en_US SET Text = '+30%[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]has 20% of its maximum HP or less[ENDCOLOR] [COLOR_POSITIVE_TEXT](active)[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_AIR_EFFECT_HELP';
	UPDATE Language_en_US SET Text = 'Unit deals Damage [COLOR:255:230:85:255]to attackng Air Unit[ENDCOLOR] (not available on Submarines). Requires [ICON_RESEARCH][COLOR_RESEARCH_STORED]Flight[ENDCOLOR]. +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS if unit [COLOR:255:230:85:255]is adjacent to another Friendly Unit[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_SEA_HELP';
	UPDATE Language_en_US SET Text = 'Bonus[ICON_MOVES]Movement Point [COLOR:255:230:85:255]after crossing Rivers[ENDCOLOR]. +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]in Rough Terrain[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SANBO_LAND_HELP';
	UPDATE Language_en_US SET Text = '+2 [ICON_SWAP] Range.' WHERE Tag = 'TXT_KEY_PROMOTION_WHITE_SANDS_HELP';
	UPDATE Language_en_US SET Text = 'Double [ICON_MOVES]Movement [COLOR:255:230:85:255]on Tundra and Snow[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_SIBERIAN_RAILWAY_HELP';
	UPDATE Language_en_US SET Text = '+5%[ICON_RANGE_STRENGTH]Offensive RCS. +2 [ICON_SWAP] Range.' WHERE Tag = 'TXT_KEY_PROMOTION_THULE_HELP';
	UPDATE Language_en_US SET Text = '+5 HP Heal [COLOR:255:230:85:255]on Heal inside Enemy Territory[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_HOSPITALLER_HELP';
	UPDATE Language_en_US SET Text = '+35%[ICON_STRENGTH]CS [COLOR:255:230:85:255]vs Mounted Units[ENDCOLOR]. Unit generates 15% [ICON_FOOD], if it [COLOR:255:230:85:255]is Garrisoned[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_TUITIO_FIDEI_HELP';

	-- Buildings
	UPDATE Language_en_US SET Text = '+50%[ICON_STRENGTH]Offensive CS/[ICON_RANGE_STRENGTH]Offensive RCS [COLOR:255:230:85:255]vs Wounded Units[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_FLETCHER_HELP';

	-- Natural Wonders
	UPDATE Language_en_US SET Text = 'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_KAILASH_HELP';
	UPDATE Language_en_US SET Text = '+10 [ICON_INFLUENCE] Influence [COLOR:255:230:85:255]after Diplomatic Mission[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ULURU_HELP';
	UPDATE Language_en_US SET Text = '+25% [ICON_WORKER] Work Rate.' WHERE Tag = 'TXT_KEY_PROMOTION_SOLOMONS_MINES_HELP';
	UPDATE Language_en_US SET Text = '+10%[ICON_RANGE_STRENGTH]Offensive RCS.' WHERE Tag = 'TXT_KEY_PROMOTION_DALLOL_HELP';
	UPDATE Language_en_US SET Text = '+1[ICON_MOVES]Movement Point. +20% [ICON_WORKER] Work Rate.' WHERE Tag = 'TXT_KEY_PROMOTION_CAUSEWAY_HELP';
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_TOURISM] [COLOR:255:230:85:255]for revealing tiles[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_MT_EVEREST_HELP';
	UPDATE Language_en_US SET Text = 'Unit gains [ICON_CULTURE] [COLOR:255:230:85:255]on Kill[ENDCOLOR]. +20%[ICON_STRENGTH]Defensive CS.' WHERE Tag = 'TXT_KEY_PROMOTION_HA_LONG_HELP';
	UPDATE Language_en_US SET Text = 'Double[ICON_MOVES]Movement [COLOR:255:230:85:255]on Snow[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_AURORA_HELP';

	UPDATE Language_en_US SET Text = '-3[ICON_MOVES]Movement Points. [COLOR_NEGATIVE_TEXT]Promotion lasts 3 turns[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_BERMUDA_TRIANGLE_HELP';
	
	UPDATE Language_en_US SET Text = '+1 [ICON_VISION] Sight. Double[ICON_MOVES]Movement and +10%[ICON_STRENGTH]CS/[ICON_RANGE_STRENGTH]RCS [COLOR:255:230:85:255]on Hills[ENDCOLOR].' WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';
END;