/*
UCS compatibility patch!
0 = Disabled disregarding if its detects UCS by Enginseer.
1 = Enabled if it detects the UCS by Enginseer.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('PO-UCS', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'PO-UCS' AND EXISTS (SELECT * FROM MinorCivilizations WHERE Type='MINOR_CIV_HONDURAS') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 0);

-- Main Compatibility Code
	-- updating texts for new promotions
	------------------------------
	-- Promotion Names
	------------------------------
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ANTANANARIVO',		'[COLOR:140:155:255:255]Pirate Haven (Antananarivo)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_BELGRADE',			'[COLOR:140:155:255:255]The White Fortress (Belgrade)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_HANOI',				'[COLOR:140:155:255:255]Patriotism (Hanoi)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_MBANZA_KONGO',		"[COLOR:140:155:255:255]Manikongo Glory (M'banza Kongo)[ENDCOLOR]"
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SIDON',				'[COLOR:140:155:255:255]Neighborhood Bully (Sidon)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_YEREVAN',			'[COLOR:140:155:255:255]Art of War (Yerevan)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT',			'[COLOR:140:155:255:255]Crusader''s Zeal (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT1',			'[COLOR:140:155:255:255]Blessing of Clermont (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT2',			'[COLOR:140:155:255:255]Onward with Haste! (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT3',			'[COLOR:140:155:255:255]United We Stand! (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT4',			'[COLOR:140:155:255:255]Charge! (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT5',			'[COLOR:140:155:255:255]Reinforce! (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT6',			'[COLOR:140:155:255:255]Glory to God! (Clermont)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_LACONIA',			'[COLOR:140:155:255:255]Spartan Discipline (Laconia)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ODENSO',				'[COLOR:140:155:255:255]Lord of the Hunt (Odenso)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_AMBRACIA',			'[COLOR:140:155:255:255]Mercenaries of Pyrrhus (Ambracia)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_DODOMA',				'[COLOR:140:155:255:255]Sail in the Wilderness (Dodoma)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_FAYA',				'[COLOR:140:155:255:255]Spoils of War (Faya)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SURREY',				'[COLOR:140:155:255:255]Magnificence in Flying Machines (Surrey)[ENDCOLOR]'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_ANTANANARIVO' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_BELGRADE' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_HANOI' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_MBANZA_KONGO' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_SIDON' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_YEREVAN' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT1' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT2' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT3' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT4' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT5' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT6' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_LACONIA' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_ODENSO' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_AMBRACIA' WHERE Type = 'PROMOTION_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_DODOMA' WHERE Type = 'PROMOTION_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_FAYA' WHERE Type = 'PROMOTION_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_SURREY' WHERE Type = 'PROMOTION_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ANTANANARIVO' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_BELGRADE' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_HANOI' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_MBANZA_KONGO' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_SIDON' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_YEREVAN' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT1' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT2' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT3' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT4' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT5' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_CLERMONT6' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_LACONIA' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_ODENSO' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_AMBRACIA' WHERE Type = 'PROMOTION_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_DODOMA' WHERE Type = 'PROMOTION_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_FAYA' WHERE Type = 'PROMOTION_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaEntry = 'TXT_KEY_PROMOTION_SURREY' WHERE Type = 'PROMOTION_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SIEGE' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_NAVAL' WHERE Type = 'PROMOTION_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_SHARED' WHERE Type = 'PROMOTION_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET PediaType = 'PEDIA_AIR' WHERE Type = 'PROMOTION_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	------------------------------
	-- Promotion Help
	------------------------------
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ANTANANARIVO_HELP',	'Unit gains [ICON_GOLD] Gold [COLOR:255:230:85:255]on Kill[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_BELGRADE_HELP',		'+25[ICON_PLUS]Total HP.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_HANOI_HELP',			'+15%[ICON_STRENGTH]CS [COLOR:255:230:85:255]inside Friendly Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_MBANZA_KONGO_HELP',	'+20%[ICON_STRENGTH]CS [COLOR:255:230:85:255]in Forest and Jungle[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SIDON_HELP',			'+5 HP [COLOR:255:230:85:255]on Heal inside Enemy Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_YEREVAN_HELP',		'Unit gains [ICON_CULTURE] Culture and [ICON_GOLDEN_AGE] Golden Age Points [COLOR:255:230:85:255]on Kill[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT_HELP',		'+33% XP [COLOR:255:230:85:255]on Fight[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT1_HELP',		'[COLOR:255:230:85:255]After first Combat[ENDCOLOR] this promotion is replaced with a randomly chosen new special promotion.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT2_HELP',		'+2[ICON_ARROW_RIGHT]Movement Points. Unit [COLOR:255:230:85:255]can Move again[ENDCOLOR] after Attack.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT3_HELP',		'+25%[ICON_STRENGTH]CS if unit [COLOR:255:230:85:255]is adjacent to another Friendly Unit[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT4_HELP',		'+15%[ICON_STRENGTH]Offensive CS. +25%[ICON_STRENGTH]CS [COLOR:255:230:85:255]vs Fortified Units[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT5_HELP',		'+15%[ICON_STRENGTH]Defensive CS. Unit [COLOR:255:230:85:255]Heals every turn[ENDCOLOR], even after performing an action.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT6_HELP',		'Unit [COLOR:255:230:85:255]imitates Great General buffs[ENDCOLOR]. +5 HP [COLOR:255:230:85:255]on Heal for this and all adjacent Friendly Units[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_LACONIA_HELP',		'+10%[ICON_STRENGTH]CS if unit [COLOR:255:230:85:255]is adjacent to another Friendly Unit[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ODENSO_HELP',		'+1[ICON_VIEW_CITY]Sight. +5 HP [COLOR:255:230:85:255]on Heal inside Neutral Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_AMBRACIA_HELP',		'Unit gains +5% [ICON_PRODUCTION] Production if unit [COLOR:255:230:85:255]is Garrisoned on Land[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_DODOMA_HELP',		'+1[ICON_MOVES]Movement Point. +5%[ICON_STRENGTH]CS.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_FAYA_HELP',			"Unit gains [ICON_RESEARCH] Science equal to 50% of defeated unit's[ICON_STRENGTH]CS [COLOR:255:230:85:255]on Kill[ENDCOLOR]."
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SURREY_HELP',		'+10%[ICON_RANGE_STRENGTH]RCS.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTANANARIVO_HELP' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_BELGRADE_HELP' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HANOI_HELP' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MBANZA_KONGO_HELP' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SIDON_HELP' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_YEREVAN_HELP' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT_HELP' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT1_HELP' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT2_HELP' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT3_HELP' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT4_HELP' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT5_HELP' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT6_HELP' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_LACONIA_HELP' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ODENSO_HELP' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_AMBRACIA_HELP' WHERE Type = 'PROMOTION_AMBRACIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_DODOMA_HELP' WHERE Type = 'PROMOTION_DODOMA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FAYA_HELP' WHERE Type = 'PROMOTION_FAYA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SURREY_HELP' WHERE Type = 'PROMOTION_SURREY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);