/*
UCS compatibility patch!
0 = Disabled disregarding if its detects UCS by Enginseer.
1 = Enabled if it detects the UCS by Enginseer.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('PO-UCS', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'PO-UCS' AND EXISTS (SELECT * FROM MinorCivilizations WHERE Type='MINOR_CIV_HONDURAS') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 0);

-- Main Compatibility Code
	-- updating texts for new promotions
	------------------------------
	-- Promotion Names
	------------------------------
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ANTANANARIVO',		'Pirate Haven (Antananarivo)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_BELGRADE',			'The White Fortress (Belgrade)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_HANOI',				'Patriotism (Hanoi)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_MBANZA_KONGO',		"Manikongo Glory (M'banza Kongo)"
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SIDON',				'Neighborhood Bully (Sidon)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_YEREVAN',			'Art of War (Yerevan)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT',			'Crusader''s Zeal (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT1',			'Blessing of Clermont (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT2',			'Onward with Haste! (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT3',			'United We Stand! (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT4',			'Charge! (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT5',			'Reinforce! (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT6',			'Glory to God! (Clermont)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_LACONIA',			'Spartan Discipline (Laconia)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ODENSO',				'Lord of the Hunt (Odenso)'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_ANTANANARIVO' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_BELGRADE' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_HANOI' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_MBANZA_KONGO' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_SIDON' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_YEREVAN' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT1' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT2' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT3' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT4' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT5' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_CLERMONT6' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_LACONIA' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Description = 'TXT_KEY_PROMOTION_ODENSO' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	------------------------------
	-- Promotion Help
	------------------------------
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ANTANANARIVO_HELP',	'Unit gains [ICON_GOLD] Gold [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_BELGRADE_HELP',		'+25 HP.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_HANOI_HELP',			'+15% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]inside Friendly Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_MBANZA_KONGO_HELP',	'+20% [ICON_STRENGTH] Combat Strength [COLOR_POSITIVE_TEXT]in Forest and Jungle[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_SIDON_HELP',			'+5 HP [COLOR_POSITIVE_TEXT]on Heal inside Enemy Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_YEREVAN_HELP',		'Unit gains [ICON_CULTURE] Culture and [ICON_GOLDEN_AGE] Golden Age Points [COLOR_POSITIVE_TEXT]on Kill[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT_HELP',		'+33% XP [COLOR_POSITIVE_TEXT]on Fight[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT1_HELP',		'[COLOR_POSITIVE_TEXT]After first Combat[ENDCOLOR] this promotion is replaced with a randomly chosen new special promotion.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT2_HELP',		'+2 [ICON_ARROW_RIGHT] Movement Points. Unit [COLOR_POSITIVE_TEXT]can Move again[ENDCOLOR] after Attack.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT3_HELP',		'+25% [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is adjacent to another Friendly Unit[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	
	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT4_HELP',		'+15% [ICON_STRENGTH] Attack Bonus. +25% [ICON_STRENGTH] vs [COLOR_POSITIVE_TEXT]Fortified Units[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT5_HELP',		'+15% [ICON_STRENGTH] Defense Bonus. Unit [COLOR_POSITIVE_TEXT]Heals every turn[ENDCOLOR], even after performing an action.'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_CLERMONT6_HELP',		'Unit [COLOR_POSITIVE_TEXT]imitates Great General buffs[ENDCOLOR]. +5 HP [COLOR_POSITIVE_TEXT]for this and all adjacent Friendly Units on Heal[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_LACONIA_HELP',		'+10% [ICON_STRENGTH] Combat Strength if unit [COLOR_POSITIVE_TEXT]is adjacent to another Friendly Unit[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	INSERT INTO Language_en_US 
				(Tag,									Text)
	SELECT		'TXT_KEY_PROMOTION_ODENSO_HELP',		'+1 [ICON_VIEW_CITY] Sight. +5 HP [COLOR_POSITIVE_TEXT]on Heal inside Neutral Territory[ENDCOLOR].'
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);

	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTANANARIVO_HELP' WHERE Type = 'PROMOTION_ANTANANARIVO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_BELGRADE_HELP' WHERE Type = 'PROMOTION_BELGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HANOI_HELP' WHERE Type = 'PROMOTION_HANOI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MBANZA_KONGO_HELP' WHERE Type = 'PROMOTION_MBANZA_KONGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SIDON_HELP' WHERE Type = 'PROMOTION_SIDON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_YEREVAN_HELP' WHERE Type = 'PROMOTION_YEREVAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT_HELP' WHERE Type = 'PROMOTION_CLERMONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT1_HELP' WHERE Type = 'PROMOTION_CLERMONT1' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT2_HELP' WHERE Type = 'PROMOTION_CLERMONT2' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT3_HELP' WHERE Type = 'PROMOTION_CLERMONT3' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT4_HELP' WHERE Type = 'PROMOTION_CLERMONT4' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT5_HELP' WHERE Type = 'PROMOTION_CLERMONT5' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CLERMONT6_HELP' WHERE Type = 'PROMOTION_CLERMONT6' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_LACONIA_HELP' WHERE Type = 'PROMOTION_LACONIA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);
	UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ODENSO_HELP' WHERE Type = 'PROMOTION_ODENSO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='PO-UCS' AND Value= 1);